[package]
name = "truntime"
version = "0.1.0"
edition = "2021"

[dependencies]
aruntime = {git = "ssh://gitea@gitea.mermaid-gecko.ts.net/Metropolis/aruntime.git"}
priority = {git = "ssh://gitea@gitea.mermaid-gecko.ts.net/Metropolis/priority.git"}
dlog = {git = "ssh://gitea@gitea.mermaid-gecko.ts.net/Metropolis/dlog.git", version = "*"}