[package]
name = "test_executors"
version = "0.1.1"
edition = "2021"
description = "Simple async executors for testing."
license = "MIT OR Apache-2.0"
homepage = "https://sealedabstract.com/code/test_executors"
repository = "https://github.com/drewcrawford/test_executors"
keywords = ["testing","async","await","future"]
categories = ["asynchronous", "concurrency", "development-tools::testing"]
exclude = [".*"]
rust-version = "1.75.0"

[dependencies]
#some_executor = ">=0"
some_executor = {git = "ssh://gitea@gitea.mermaid-gecko.ts.net/Metropolis/some_executor"}
priority = ">=0"
logwise = ">=0.1.1"
blocking_semaphore = ">=0"
