#!/bin/bash
set -e
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

if [[ " $* " =~ " --relaxed " ]]; then
    export RELAXED_WARNINGS=1
fi
source "$SCRIPT_DIR/_env"
CARGO_TARGET_WASM32_UNKNOWN_UNKNOWN_RUNNER="wasm-bindgen-test-runner" RUSTFLAGS="$WASM32_RUSTFLAGS" RUSTDOCFLAGS="$WASM32_RUSTDOCFLAGS" cargo +nightly test --target=wasm32-unknown-unknown

# Run proc crate tests
cd "$REPO_ROOT/test_executors_proc"
"$REPO_ROOT/test_executors_proc/scripts/wasm32/tests" "$@"
